
CREATE TABLE PIZZA_ITEMS(ID INT AUTO_INCREMENT PRIMARY KEY,Name VARCHAR(40),Type VARCHAR(20),Category VARCHAR(30),Description VARCHAR(120));
CREATE TABLE PIZZA_PRICING(ID INT AUTO_INCREMENT PRIMARY KEY, ITEMID INT REFERENCES PIZZA_Items, SIZES VARCHAR(20), Price DOUBLE);
CREATE TABLE PIZZA_CUSTOMERS(ID INT AUTO_INCREMENT PRIMARY KEY,Name VARCHAR(30),Password VARCHAR(15),Mobile VARCHAR(15),Address VARCHAR(60),Email VARCHAR(40), CONSTRAINT EMAIL_UNIQUE UNIQUE (Email)); 
CREATE TABLE PIZZA_ORDERS(ID INT AUTO_INCREMENT PRIMARY KEY,CustomerId INT,OrderTime DATETIME, STATUS VARCHAR(12));
CREATE TABLE PIZZA_ORDERDETAILS(ID INT AUTO_INCREMENT PRIMARY KEY, OrderId INT REFERENCES PIZZA_Orders, PRICEID INT REFERENCES PIZZA_Pricing);
